name: 'nhs_pca'
version: '1.0.0'
config-version: 2

profile: 'nhs_pca'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  nhs_pca:
    +materialized: table
    gold_layer:
      +materialized: table